- database/migrations/2018_06_22_111322_create_posts_db.php
Created migration 'create_posts_db', which sets up database tables 'posts_data',
'posts_labels', 'posts_images' and 'posts_authors'
Closes #2
> feat(posts): create migration 'create_posts_db'

- app/Models/Posts.php
- app/Models/Posts/Authors.php
- app/Models/Posts/Images.php
- app/Models/Posts/Labels.php
- database/migrations/2018_06_22_111322_create_posts_db.php
> feat(posts): Add Posts model

- .gitignore
- .php_cs
- .travis.yml
- app/Models/Posts.php
- app/Models/Posts/Authors.php
- app/Models/Posts/Images.php
- app/Models/Posts/Labels.php
- composer.json
- composer.lock
- database/migrations/2018_06_22_111322_create_posts_db.php
> feat(style): Add linter

- app/Http/Controllers/PostsController.php
- app/Models/Events.php
- database/factories/PostsFactory.php
- database/migrations/2018_06_22_111322_create_posts_db.php
- database/migrations/2018_07_02_185240_create_events_db.php
- routes/api.php
- Longer seeds for Posts content & description (#42 )
- Posts content field type set to longText (#43 )
> Longer seeds for Posts content and description

- app/Models/Canteens.php
- app/Models/Canteens/Menus.php
- Created class `App\Models\Canteens`
- Created class `App\Models\Canteens\Menus`
Closes #30
> feat(canteen): Canteen models

- app/Http/Controllers/CanteensController.php
- routes/api.php
If applied this PR will add `getCanteenMenus` API endpoint
Closes #33
> feat(canteen): Add getCanteenMenus API endpoint

- app/Models/Posts.php
- database/factories/PostsFactory.php
- database/migrations/2018_06_22_111322_create_posts_db.php
If applied, this PR will add the property `color` to class `App\Models\Posts`, and updates the its migration and factory
> Issue49: Add color for Posts table and model

- app/Http/Controllers/CanteensController.php
- routes/api.php
If applied, this PR will add `getCanteenByWeek` API endpoint
Closes #32
> feat(canteen): Add getCanteenByWeek API endpoint

- app/Http/Controllers/CanteensController.php
- app/Http/Controllers/EventsController.php
- app/Http/Controllers/PostsController.php
If applied, this PR will add **parameter existence-checks, validation and result emptiness checks** 
to `PostsController`, `EventsController` and `CanteensController`, 
as well as their corresponding **HTTP error codes**
Closes #50
> Issue50: Refactor HTTP response codes

- .travis.yml
> build(travis): Add code coverage

- .travis.yml
- app/Http/Controllers/CanteensController.php
- tests/Feature/CanteenAPITest.php
- tests/Feature/EventsAPITest.php
- tests/Feature/PostsAPITest.php
- tests/Feature/TestsBase.php
If applied, this PR will add unittesting for the following APIs:
- `PostsAPI`
- `CanteenAPI`
- `EventsAPI`
Closes #64
> Issue64: Add API testing

- app/Http/Controllers/CanteensController.php
- app/Http/Controllers/ControllerBase.php
- app/Http/Controllers/EventsController.php
- app/Http/Controllers/PostsController.php
- app/Models/Canteens.php
- app/Models/Canteens/Menus.php
- app/Models/Events.php
- app/Models/Posts.php
- app/Models/Posts/Images.php
- composer.lock
- database/migrations/2018_06_22_111322_create_posts_db.php
- database/migrations/2018_07_01_120118_create_canteen_db.php
- database/migrations/2018_07_02_185240_create_events_db.php
- tests/Feature/CanteenAPITest.php
- tests/Feature/EventsAPITest.php
- tests/Feature/PostsAPITest.php
- tests/Feature/TestsBase.php
If applied, this PR will add the handling of the `If-modified-since` request header for the following controller classes:
- `App\Http\Controllers\PostsController` for __Posts API__
- `App\Http\Controllers\EventsController` for __Events API__
- `App\Http\Controllers\CanteensController` for __Canteen API__
It will also fix issues #58, #59, #60, #69
Closes #52 
Fixes #58, fixes #59, fixes #60, fixes #69
> Issue52: Use If-Modified-Since request header

- app/Http/Controllers/NewsletterController.php
- app/Models/Newsletter.php
- composer.lock
- database/factories/NewsletterFactory.php
- database/migrations/2018_07_21_254553_create_newsletter_db.php
- database/seeds/DatabaseSeeder.php
- database/seeds/NewsletterSeeder.php
- routes/api.php
- tests/Feature/NewsletterAPITest.php
> feat: Add basic newsletter API

- app/Http/Controllers/Admin/EventsCrudController.php
- app/Http/Requests/EventsRequest.php
- app/Models/Events.php
- resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
- routes/backpack/custom.php
If applied, this commit will add a simple admin panel for Events
Closes #108
> feat: Admin panel for Events

- app/Http/Controllers/Admin/CanteensCrudController.php
- app/Http/Controllers/Admin/MenusCrudController.php
- app/Http/Requests/CanteensRequest.php
- app/Http/Requests/MenusRequest.php
- app/Models/Canteens.php
- app/Models/Canteens/Menus.php
- resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
- routes/backpack/custom.php
If applied, this PR will add basic admin panels for `Canteens\Menus` and `Canteens`
> Issue107: Admin panel for Canteens

- database/seeds/DatabaseSeeder.php
- database/seeds/UserSeeder.php
Name: **test**
Email: **test@test.test**
PWD: **test**
> Issue131: Default user seeder

- .psysh.php
I added the config from the linked comment
> Fix: Tinker issue on production

- config/backpack/base.php
Do an `php artisan config:cache` in order to work!
> Updated config/backpack/base.php

- app/Http/Controllers/CanteensController.php
Fixed by implementing a sorting
Fixes #229
> fix: Canteen array from API is not ordered by type

- app/Http/Controllers/Admin/ColleaguesCrudController.php
- app/Http/Controllers/Controller.php
- app/Http/Requests/ColleaguesRequest.php
- database/migrations/2019_04_02_205431_add_colleagues_permissions.php
- resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
> Issue234 - add colleagues permissions to adminpanel

- app/Http/Controllers/NewsletterController.php
- tests/Feature/NewsletterAPITest.php
See issue description
Fixes #276
> fix: Broken newsletter API & tests

- app/Http/Controllers/NewsletterController.php
> fix: Newsletter API tests

- app/Http/Requests/AuthorsRequest.php
- app/Http/Requests/LabelsRequest.php
- database/migrations/2019_10_10_234945_posts_permissions.php
Add separate permissions to edit posts, labels & authors
> Writer permissions

- app/Http/Controllers/Admin/PostsCrudController.php
- app/Models/Posts.php
> fix: date field not showing prev. value

- app/Http/Controllers/PostsController.php
Grouped where clauses.
Fixes #305, fixes #303
> Issue305: Search endpoint showing hidden posts

- app/Http/Controllers/Admin/PostsCrudController.php
> Issue301: Can not create featured posts

- database/migrations/2019_01_09_020956_add_featured_to_posts.php
> fix: 'add_featured_to_posts' migration's down

- app/Http/Controllers/Admin/PostsCrudController.php
> feat: Set default Post type in adminpanel

- app/Http/Requests/PostsRequest.php
Set a limit in PostsRequest.php (60kB)
Closes #333
> feat: Size limit for posts index images

- .docker/app.dockerfile
Updated to use mariadb-client instad of mysql-client
Fixes #332
> fix: Update app.dockerfile

- app/Http/Controllers/PostsController.php
> feat: change the number of featured posts returned

- app/Http/Controllers/ColleaguesController.php
> fix: fix ordering with colleagues names

- app/Http/Controllers/Admin/ColleaguesCrudController.php
- database/factories/ColleaguesFactory.php
- database/migrations/2020_01_21_202750_change_colleagues_types.php
> Issue348: change colleagues categories

- app/Http/Controllers/Admin/ColleaguesCrudController.php
> fix: lowercase 'l' in colleagues adminpanel

- app/Http/Controllers/Admin/PostsCrudController.php
> feat: Enable table button for simplemde
